# Generated by Django 2.1.2 on 2018-10-24 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeReportEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('hours_worked', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('job_group', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('time_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.TimeReport')),
            ],
        ),
    ]
